spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=demoproject1031@gmail.com
spring.mail.password=zsranzjoyloxxkth

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true